version: '3.9'
services:
  db:
    image: mysql:8.3
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: tudu3
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: tudu
      MYSQL_PASSWORD: tudu
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
volumes:
  db-data:


